name: Check PR Base

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  prevent-non-devnet-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR targets main from a branch other than devnet
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"
          
          echo "Base branch: $BASE_BRANCH"
          echo "Head branch: $HEAD_BRANCH"

          if [ "$BASE_BRANCH" = "main" ] && [ "$HEAD_BRANCH" != "devnet" ]; then
            echo "Any feature branch needs to be merged to devnet branch first."
            exit 1
          else
            echo "PR does not violate the rule."
          fi
