name: Check PR Branch

on:
  pull_request: # Trigger on all PR event types

jobs:
  check-pr-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Get base and head branch names
        id: vars
        run: |
          echo "BASE_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
          echo "HEAD_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      - name: Fetch base branch
        run: |
          git fetch origin $BASE_BRANCH
          git checkout $BASE_BRANCH

      - name: Check for merge commits
        run: |
          git checkout $HEAD_BRANCH
          if git log --merges origin/$BASE_BRANCH..HEAD | grep -q .; then
            echo "Merge commits found in the PR branch."
            exit 1
          else
            echo "No merge commits found."
          fi

      - name: Check if PR branch is rebased
        run: |
          git checkout $HEAD_BRANCH
          if ! git merge-base --is-ancestor origin/$BASE_BRANCH HEAD; then
            echo "PR branch is not rebased on top of $BASE_BRANCH."
            exit 1
          else
            echo "PR branch is rebased on top of $BASE_BRANCH."
          fi
