name: Label PRs with devnet base

on:
  push:
    branches:
      - devnet

jobs:
  label-prs-with-devnet-base:
    runs-on: ubuntu-latest

    steps:
      - name: Label PRs with devnet base
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const baseBranch = "devnet"; // Base branch to filter
            const labelName = "devnet-push"; // Label to apply and remove

            // Fetch open pull requests with the base branch 'devnet'
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              base: baseBranch,
            });

            if (pullRequests.length === 0) {
              console.log("No open pull requests with base branch 'devnet'.");
            } else {
              console.log(`Found ${pullRequests.length} pull request(s) with base branch 'devnet'.`);

              for (const pr of pullRequests) {
                console.log(`Processing PR #${pr.number}`);

                // Add the label
                console.log(`Adding label "${labelName}" to PR #${pr.number}`);
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  labels: [labelName],
                });

                // Remove the label
                console.log(`Removing label "${labelName}" from PR #${pr.number}`);
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  name: labelName,
                });
              }
            }
