name: Label PRs on devnet push

on:
  push:
    branches:
      - devnet

jobs:
  label-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Add label to all PRs with devnet base
        uses: actions/github-script@v6
        with:
          script: |
            const baseBranch = "devnet"; // Base branch to filter
            const labelName = "devnet"; // Label to apply

            // Fetch open pull requests with the base branch as 'devnet'
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              base: baseBranch,
            });

            if (pullRequests.length === 0) {
              console.log("No open pull requests with base branch 'devnet'.");
            } else {
              console.log(`Found ${pullRequests.length} pull request(s) with base branch 'devnet'.`);
              for (const pr of pullRequests) {
                console.log(`Adding label to PR #${pr.number}`);
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  labels: [labelName],
                });
              }
            }
