name: Validate devnet non-main PR

on:
  pull_request:
    branches:
      - devnet
  push:
    branches:
      - devnet

jobs:
  validate-devnet-non-main-pr:
    runs-on: ubuntu-latest

    # Skip the job if the base or head branch is 'main'
    if: github.event.pull_request.base.ref != 'main' && github.event.pull_request.head.ref != 'main'

    steps:
      # Checkout the branch
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history to inspect commits

      # Ensure branch is rebased on top of latest devnet
      - name: Check if branch is up-to-date with devnet
        run: |
          # Fetch the latest devnet branch
          git fetch origin devnet

          # Compare the base of the branch to the devnet branch
          BASE_COMMIT=$(git merge-base HEAD origin/devnet)
          if [ "$BASE_COMMIT" != "$(git rev-parse origin/devnet)" ]; then
            echo "The branch is not rebased on top of the latest devnet branch."
            echo "Please rebase your branch on top of devnet."
            exit 1
          fi
        shell: bash

      # Ensure no merge commits exist
      - name: Check for merge commits
        run: |
          # List all merge commits in the branch
          MERGE_COMMITS=$(git log --merges --oneline origin/devnet..HEAD)
          if [ -n "$MERGE_COMMITS" ]; then
            echo "Merge commits are not allowed in this branch."
            echo "Please rebase your branch and remove the following merge commits:"
            echo "$MERGE_COMMITS"
            exit 1
          fi
        shell: bash
