name: Validate devnet non-main PR

on:
  pull_request:
    branches:
      - devnet
  push:
    branches:
      - devnet

jobs:
  validate-devnet-non-main-pr:
    runs-on: ubuntu-latest

    # First, check if the event is associated with a pull request
    # Then skip the job if the base or head branch is 'main'
    if: github.event.pull_request != null && github.event.pull_request.base.ref != 'main' && github.event.pull_request.head.ref != 'main'

    steps:
      # Checkout the branch
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to inspect commits

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if head branch is rebased on top of base branch
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"

          echo "Base Branch: $BASE_BRANCH"
          echo "Head Branch: $HEAD_BRANCH"

          # Get the latest commit hash of both base and head branch
          BASE_HASH=$(git log -n 1 --pretty=format:"%H" origin/$BASE_BRANCH)
          HEAD_HASH=$(git log -n 1 --pretty=format:"%H" origin/$HEAD_BRANCH)

          # Check if the head branch is directly rebased on top of base branch
          BASE_PARENT=$(git log --pretty=format:"%P" -n 1 $BASE_HASH)

          if [[ "$BASE_PARENT" != "$HEAD_HASH" ]]; then
            echo "The head branch is not rebased on top of the base branch."
            exit 1
          else
            echo "The head branch is rebased on top of the base branch."
          fi

      # Ensure no merge commits exist
      - name: Check for merge commits
        run: |
          # Check for merge commits between the head branch and the base branch
          BASE_BRANCH=${GITHUB_EVENT_PULL_REQUEST_BASE_REF}
          MERGE_COMMITS=$(git log --merges --oneline origin/$BASE_BRANCH..HEAD)
          if [ -n "$MERGE_COMMITS" ]; then
            echo "Merge commits are not allowed in this branch."
            echo "Please rebase your branch and remove the following merge commits:"
            echo "$MERGE_COMMITS"
            exit 1
          fi
        shell: bash
