name: Validate devnet non-main PR

on:
  pull_request:
    branches:
      - main
      - devnet
  push:
    branches:
      - devnet

jobs:
  validate-devnet-non-main-pr:
    runs-on: ubuntu-latest

    # Skip the job if the base or head branch is 'main', or if the push isn't part of a PR
    if: github.event.pull_request.base.ref != 'main' && github.event.pull_request.head.ref != 'main' && github.event.pull_request != null

    steps:
      # Checkout the branch
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to inspect commits

      # Ensure branch is rebased on top of the latest base branch
      - name: Check if branch is rebased on top of the base branch
        run: |
          # Fetch the latest base branch
          BASE_BRANCH=${GITHUB_EVENT_PULL_REQUEST_BASE_REF}
          git fetch origin $BASE_BRANCH

          # Compare the base of the head branch to the base branch
          BASE_COMMIT=$(git merge-base HEAD origin/$BASE_BRANCH)
          if [ "$BASE_COMMIT" != "$(git rev-parse origin/$BASE_BRANCH)" ]; then
            echo "The branch is not rebased on top of the latest $BASE_BRANCH branch."
            echo "Please rebase your branch on top of $BASE_BRANCH."
            exit 1
          fi
        shell: bash

      # Ensure no merge commits exist
      - name: Check for merge commits
        run: |
          # Check for merge commits between the head branch and the base branch
          BASE_BRANCH=${GITHUB_EVENT_PULL_REQUEST_BASE_REF}
          MERGE_COMMITS=$(git log --merges --oneline origin/$BASE_BRANCH..HEAD)
          if [ -n "$MERGE_COMMITS" ]; then
            echo "Merge commits are not allowed in this branch."
            echo "Please rebase your branch and remove the following merge commits:"
            echo "$MERGE_COMMITS"
            exit 1
          fi
        shell: bash
